### ISSUE TITLE
Support mongoose 5

### ISSUE THREAD

**Issue by capaci** [mimani/mongoose-diff-history#31] opened 2018-06-04 23:00 UTC
Mongoose 5 was released a few months ago.

Is there any intention of updating the mongoose-diff-history to support it?

In any case, here's the how-to-upgrade: https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md

I could try to update, I don't think there should be big issues with it :-)

**Comment by mimani** [comment] 2018-06-07 11:28
We can do it, only thing we have to make sure is its backward compatible. You can go ahead, Please let us know your plan.

**Comment by AbdelrahmanHafez** [comment] 2018-09-10 11:52
So, we're having an issue on a project that causes the only diff being logged is updatedAt, all the other fields are not being updated. One of our developers will be creating a PR soon.

I think this may be related to migrating to mongoose 5.

**Comment by JonasRech** [comment] 2018-12-17 12:57
I am also faced with the problem that only updatedAt is taken into consideration. Is there already a fix for the problem?

**Comment by JonasRech** [comment] 2018-12-17 13:33
> So, we're having an issue on a project that causes the only diff being logged is updatedAt, all the other fields are not being updated. One of our developers will be creating a PR soon.
> 
> I think this may be related to migrating to mongoose 5.

@AbdelrahmanHafez I think I've found a temporary solution. Just give $set when you call UpdateOne.
`const writeOpResult = await Collection.updateOne({ _id }, { $set: { xyz: 'abc' } });`

The problem is this line in source code
`const updateParams = queryObject._update['$set'] || queryObject._update;`

**Comment by mimani** [comment] 2019-03-10 11:33
The issue has been fixed with latest [release](https://www.npmjs.com/package/mongoose-diff-history/v/1.6.1).

**Closed by mimani** 2019-03-10 11:33 UTC
